client_id           = ""
client_secret       = ""
tenant_id           = ""
subscription_id     = ""
resource_group_name = ""
environment         = ""
prefix              = ""
location            = "westeurope"
